title:              JUG MERIDA
email:              gugmerida@gmail.com
description:        Site for JUG Merida
author:             Start Bootstrap
baseurl:            "/jug-site"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   jug-merida
github_username:    jug-merida


# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
